<?php
$title = $this->getTitle();
$identify = $this->getIdentify();
$categoryIds = $this->getCatIds();
$categoryIds = explode(',', $categoryIds);
$_helper = $this->helper('catalog/output');
$productsOnRow = $this->getProductsOnRow();
if(!$productsOnRow) $productsOnRow = 3;
if ( !$this->getWidthThumbnail() ){
	$w_thumbnail = 135;
} else {
	$w_thumbnail = $this->getWidthThumbnail();
}
if( !$this->getHeightThumbnail() ){
	$h_thumbnail = 135;
 }
else {
	$h_thumbnail = $this->getHeightThumbnail();
}
?>

<?php

        $item_width = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/item_width');
        $items_show = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/items_show');
        $speed = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/speed');
        $interval = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/interval');
        $nav_ctrl = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/nav_ctrl');
        $next_back = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/next_back');
        $show_price = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/show_price');
        $review = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/show_review');
	$addtowishlist = Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/addtowishlist');
	$addtocompare =  Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/addtocompare');
	$addtocart =  Mage::getStoreConfig('categorytabsliders/categorytabsliders_config/addtocart');
		$title = $this->getTitle();
?>
<div id="container">
	<div class="categorytabsliders-title"><?php echo '<h2>'.$title.'</h2>'; ?></div>
  <ul class="tabs tabs<?php echo '-'.$identify;?>  tab_categorys"> 
   <?php 
	$k = 0;
	foreach($categoryIds as $cate_id) {
		$cate_model = Mage::getModel('catalog/category');
		$cateName = $cate_model->load($cate_id)->getName();
		
		if($cateName) {
   ?>
			<li class="<?php if($k==0){ echo "active"; }?>" rel="tab<?php echo $cate_id.'-'.$identify;?>"><span class="tab-categories tab<?php echo $cate_id;?>"><span><?php  echo $cateName; ?></span></span></li>
	<?php }  $k++; } ?>
    </ul>

	<div class="tab_slider_container"> 
		<?php foreach($categoryIds as $cate_id) {
		?>
		 <div id="tab<?php echo $cate_id.'-'.$identify;?>" class="tab_content_<?php echo $identify; ?>"> 
			<?php $_productCollection = $this->getProductCate($cate_id); ?>
			<?php $_collectionSize = $_productCollection->count() ?>
			<?php $_columnCount = $productsOnRow; ?>
		<ul class="bxslider">	
		<?php $i=0; foreach ($_productCollection as $_product): ?>
		
				<li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>" style ="width:<?php echo $item_width; ?>px !important">
					<div class="item-container">
						<div class="item-inner">
							<div class="item-inner-top">
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w_thumbnail, $h_thumbnail); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
								<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
								<?php if($review) { ?>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								<?php } ?>
								<?php if( $show_price) { echo $this->getPriceHtml($_product, true); } ?>
							</div>
							
							<div class="des-inbox">
								<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
								<?php if($review) { ?>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								<?php } ?>
								<?php if( $show_price) { echo $this->getPriceHtml($_product, true); } ?>
								<div class="actions">
									<?php if($_product->isSaleable()): ?>
										<?php if($addtocart) { ?>
											<button type="button" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
										<?php } ?>
									<?php else: ?>
										<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									<?php endif; ?>
									
								</div>
								
							</div>
							<ul class="add-to-links">
										<?php if($addtowishlist) { ?>
											<?php if ($this->helper('wishlist')->isAllow()) : ?>
												<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist')?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
											<?php endif; ?>
										<?php }  ?>
										<?php if($addtocompare) { ?>
											<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
												<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare')?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
											<?php endif; ?>
										<?php }  ?>
									</ul>
							
						</div>
						<?php
							$newFromDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsFromDate();
							$newToDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsToDate();                 
							$now = date("Y-m-d H:m(worry)");
							// Get the Special Price
							$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
							// Get the Special Price FROM date
							$specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
							// Get the Special Price TO date
							$specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
							// Get Current date
							if ($specialprice&&($specialPriceFromDate <= $now && $specialPriceToDate >= $now)&& Mage::getStoreConfig('themeoptions/themeoptions_config/sale_label')){
								echo "<span class='sale'></span>";
								}else{
								if($newFromDate <= $now && $newToDate >= $now && Mage::getStoreConfig('themeoptions/themeoptions_config/new_label') ) {
									echo "<span class='new'></span>";
									//echo $now.' -- '.$newsFrom.' -- '.$newsTo;
								}
							}
						?>
					</div>
				</li>
			
			
			<?php endforeach ?>
			</ul>		
			<script type="text/javascript">
						$jq(document).ready(function(){
							<?php $idBx = '#tab'.$cate_id.'-'.$identify.' .bxslider'; ?>
						  $jq("<?php echo $idBx; ?>").bxSlider(
							{
							  speed: <?php echo $speed; ?>,
							  pause: <?php echo $interval; ?>,			  
							  minSlides: 2,
							  maxSlides: <?php echo $items_show ?>,
							  slideWidth: <?php echo $item_width ?>,
							  slideMargin: 28,
							<?php if ($nav_ctrl) { ?>
							  pager: true,
							<?php } else { ?> 
							  pager:false, 
							<?php } ?>
							<?php if ($next_back) { ?>
								controls: true,
							<?php } else { ?>
								controls:false,
							<?php } ?>
							}
						  );
						});
					</script>
		 </div><!-- #tab1 -->
		 <?php }?>

		 
	 </div> <!-- .tab_container --> 

</div> <!-- #container -->

<script type="text/javascript">

$jq(document).ready(function() {
	
	$jq(".tab_content_<?php echo $identify; ?>").hide();
	$jq(".tab_content_<?php echo $identify; ?>:first").show(); 

	$jq("ul.tabs<?php echo '-'.$identify;?> li").click(function() {
		$jq("ul.tabs<?php echo '-'.$identify;?> li").removeClass("active");
		$jq(this).addClass("active");
		$jq(".tab_content_<?php echo $identify; ?>").hide();
		var activeTab = $jq(this).attr("rel"); 
		$jq("#"+activeTab).fadeIn(); 
	});
});

</script> 
<style type="text/css">
@-moz-document url-prefix() {
	.tab_slider_container .item {
		width:<?php echo $item_width; ?>px !important;
	}
}
</style>